### PR TITLE
UNI Integration + Minor QoL Additions

### PR DESCRIPTION
**Pull request by tsorz**
**Changes**:

- **cli.py** --> Added additional vars to "preprocess" (var "**feat_extractor**": str("ctp" or "uni") and "heatmaps" (var "**overview**": bool -> option to turn off overview image creation as it takes ages to finish as opposed to just tiles + scores heatmap)
- **config.yaml** --> Added aformentioned **cli.py** vars to **config.yaml**
- **heatmaps/__main__.py** --> Modified code to only generate overview image if **config.yaml/overview == True**
- **preprocessing/helpers/feature_extractors.py** --> new class **FeatureExtractorUNI**; loads UNI feature extractor in **wsi_norm.py**
- **preprocessing/wsi_norm.py** --> Modified to correctly load CTransPath or UNI depending on **config.yaml/feat_extractor** variable
- Added **extract_attention.py** script --> Compatible with attMIL models trained with marugoto. Convenience script in case somebody wants to quickly get a full attention-weight dataframe from a pre-defined model. 
- Minor changes to README instructions for addition of UNI. 

**Issues**: 

- [x] stamp heatmaps raises "ModuleNotFound" error (can't find marugoto) unless the marugoto repository is specifically cloned and installed. Tested with main STAMP branch and found the same issue. However, tested this only when trying to create heatmaps using models trained with main marugoto branch. Did not test with models trained using STAMP transformers.  --> Could add instructions to additionally pip install marugoto

### CODE REVIEW

**Comment by Avic3nna** [comment]
Hi Thomas, thank you so much for the PR! We were just about to include UNI. It's indeed a tricky one due to their signing up procedure etc... It makes the "smoothness" of STAMP substantially lower, as well as making the instructions bulky and very UNI-centered, as we now went to running 1 command to download everything, to now actually having to clone stuff (before not necessary). Now that I see it implemented like this, perhaps we should move this to the E2E pipeline @cornzz for advanced users, and keep STAMP lean? 🤔

Regarding the issue: that's intended behavior. I don't think we should mix and match marugoto/STAMP models. This won't happen when training STAMP models and then create the heatmaps (intended use).

**Comment by tsorz** [comment]
Thanks for the quick response! 

Fully agree with the "smoothness" argument - As I sent the PR I thought that it probably makes sense to have the UNI integration as a separate branch. 

Heatmaps: Got it - I figured it had something to do with the type of model I tried to make heatmaps from. :)

If there is anything else I can do let me know ^^

**Comment by Avic3nna** [comment]
Actually, looking closer we can incorporate all the installation steps of UNI as part of STAMP. Then the user does not have any "additional" steps for installation besides having to sign up for huggingface and get approved (optional). However, I cannot accept only a part of your pull request - so it's all or nothing 😄

**Comment by tsorz** [comment]
Hey Omar - Thanks for your feedback. I made it UNI-compatible with pretty much no changes to installation instructions. 
I did however keep the two additional vars in the config - At least for preprocessing I think it is necessary to define ctp or uni. For heatmaps it is easy to remove the additional "overview" var. 
If you want, you can take over this version. Or if you plan to do other upgrades, feel free to also close this PR ^^

**Pull request merged**
